#!/usr/bin/env bash

cd "$(dirname "$0")/../.."
. script/environment

cp -r ${VCV_PLUGIN_CHECKOUT_DIR} ${VCV_PLUGIN_DIR}

if ((VCV_DEBUG >= 1)); then
    cd ${VCV_PLUGIN_DIR}
    git log -1 --decorate=full --pretty=oneline
    ls -FGhlR
fi

cd ${VCV_PLUGIN_DIR}

make dist VERSION=${VCV_BUILD_TAG}

if ((VCV_DEBUG >= 1)); then
    ls -FGhl
    ls -FGhlR dist
fi

rm -rf ${VCV_PLUGIN_ARTIFACT_DIR}
mkdir -p ${VCV_PLUGIN_ARTIFACT_DIR}
mv ${VCV_PLUGIN_DIST_FILE} ${VCV_PLUGIN_ARTIFACT_DIR}

if ((VCV_DEBUG >= 1)); then
    cd ${VCV_PLUGIN_ARTIFACT_DIR}
    ls -FGhlR
fi
