baseURL: "https://dhemery.github.io/DHE-Modules"
languageCode: "en-us"
title: DHE Modules
params:
    SubTitle: VCV Rack modules from Dale Emery
    Repository: "https://github.com/dhemery/DHE-Modules/"
copyright: © 2017–2021 Dale H. Emery
canonifyUrls: true
disableKinds:
    - sections
    - taxonomy
    - term
    - RSS
    - sitemap
markup:
    goldmark:
        renderer:
            unsafe: true
