require 'rake/clean'
require 'pathname'
require 'oj'
require_relative 'lib/module'

$modules_dir = Pathname('modules')
$module_json_files = $modules_dir.glob('*.json')
$modules = $module_json_files
               .map {|f| DHE::Module.new(json_file: f)}

$svg_dir = Pathname('_svg')
$image_dir = Pathname('_images')

directory $image_dir
directory $svg_dir

task default: [:all] do
end

task all: [:controls, :modules, :images] do
end

# SVG files for the manual (panels with controls)
task images: [$image_dir] do
  $modules
      .map(&:manual_image_file)
      .each {|f| f.write($image_dir)}
end

# SVG files for module faceplates (sans controls)
task modules: [$svg_dir] do
  $modules
      .map(&:faceplate_file)
      .each {|f| f.write($svg_dir)}
end

# SVG files for the individual controls
task controls: [$svg_dir] do
  $modules
      .flat_map(&:control_files)
      .each {|f| f.write($svg_dir)}
end

desc 'Clobber all files, then build all SVG files'
task fresh: [:clobber, :default]

CLEAN.include $image_dir, $svg_dir
