#!/usr/bin/env bash

cd "$(dirname "$0")/../.."
. script/environment

if [[ -n ${APPVEYOR-} ]] ; then
    pacman -S --noconfirm zip unzip mingw-w64-x86_64-cmake
fi

cd ${VCV_RACK_DIR}

make dep > /dev/null
make

if ((VCV_DEBUG >= 1)); then
    ls -FGhl
fi