#!/usr/bin/env bash

cd "$(dirname "$0")/../.."
. script/environment

git clone https://github.com/VCVRack/Rack.git ${VCV_RACK_DIR} || true

cd ${VCV_RACK_DIR}
git pull
git submodule update --init --recursive

if ((VCV_DEBUG >= 1)); then
    git log -1 --decorate=full --pretty=oneline
    ls -FGhl
fi
