@startuml
[*] --> Input

Defer : ACTIVE : true
Defer --> Input : DEFER ⇩

Generate : ACTIVE : true
Generate --> Defer : DEFER ⇧
Generate --> Generate : TRIG ⇧
Generate --> Level : Stage Completed

Input : ACTIVE : false
Input --> Defer : DEFER ⇧
Input --> Generate : TRIG ⇧

Level : ACTIVE : false
Level --> Defer : DEFER ⇧
Level --> Generate : TRIG ⇧

@enduml

