#!/usr/bin/env bash
set -o errexit
set -o nounset

echo "MSYSTEM=${MSYSTEM}"

export VCV_BUILD_DIR="C:\projects"

export VCV_RACK_BUILD_DIR="${VCV_BUILD_DIR}/Rack"
export VCV_RACK_PLUGINS_DIR="${VCV_RACK_BUILD_DIR}/plugins"

export VCV_PLUGIN_NAME=DHE-Modules
export VCV_PLUGIN_ARTIFACT_DIR="${APPVEYOR_BUILD_FOLDER}/artifacts"
export VCV_PLUGIN_BUILD_DIR="${VCV_RACK_PLUGINS_DIR}/${VCV_PLUGIN_NAME}"

env | sort

set -o xtrace

git clone https://github.com/VCVRack/Rack.git "${VCV_RACK_BUILD_DIR}" || true
cd "${VCV_RACK_BUILD_DIR}"
git pull
git submodule update --init --recursive
make dep > /dev/null
make

cp -r "${APPVEYOR_BUILD_FOLDER}" "${VCV_PLUGIN_BUILD_DIR}"
cd "${VCV_PLUGIN_BUILD_DIR}"
make clean test dist

ls -FlagsR dist

mkdir -p "${VCV_PLUGIN_ARTIFACT_DIR}"
cp dist/*.zip "${VCV_PLUGIN_ARTIFACT_DIR}/"
