name: C/C++ CI

on:
  push:
    branches: [ develop, wip/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make test
    - name: make dist
      run: make dist
